//单笔信贷核发申请查询信息
public without sharing  class AMCreditAuditing {
	public String status {get;set;}   //状态
    public String vbeln {get;set;}   //销售凭证
	public String  vgbel {get;set;}      
	public String kunnr {get;set;} 
	public String name {get;set;}   
	public String ctlpc {get;set;}   
	public String rtext {get;set;} 
	public String zterm {get;set;}   
	public String text1 {get;set;} 
	public String bstkd {get;set;}   
	public String olikw {get;set;}  
	public String ofakw {get;set;}   
	public String klimk {get;set;}   
	public String zsolikw {get;set;}   
	public String vkorg {get;set;}

	public String skfor {get;set;}   
	public String zdmbtr {get;set;}   
	public String zdtr916 {get;set;}  

	public String gl {get;set;}   
	public String ssobl {get;set;}   
	public String netwr {get;set;}     
}