public with sharing class SiteMaterialJsonReturn {
    public String direction {GET;SET;}
    public String logo {GET;SET;}
    public String langu {GET;SET;}
    public String is_bpe {GET;SET;}
    public String is_stamp {GET;SET;}
    public String is_quan {GET;SET;}
    public String is_order {GET;SET;}
    public String sp_flag {GET;SET;}
   
   public void TestPass(){
   	Integer aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   	 aa = 1;
   }
}